<?php

return [
    'version' => "0.8 ALPHA",
    'blog_prefix' => "blog",
    'panel_prefix' => "panel",
    'files_disk' => "blublog",
    'img_height' => 600,
    'img_height_type' => "int",
    'img_width' => 350,
    'img_width_type' => "int",
    'img_quality' => 60,
    'img_quality_type' => "int",
    'post_editor' => true,
    'post_editor_type' => "bool",
    'footer_html' => "Based on Bootstrap. Icons from Font Awesome. Web fonts from Google.<br>Blog made with <a href='https://blublog.info'>BLUblog</a>.",
    'footer_html_type' => "text",
    'head_html' => "<h1>Welcome to BLUblog!</h1><p>This is info panel for front page that can be edited or removed.<p>",
    'head_html_type' => "text",
    'sidebar_html' => "<div class='alert alert-primary' role='alert'>This is sidebar html area. Could be edited or removed.</div>",
    'sidebar_html_type' => "text",
    'site_name' => "BLUblog",
    'site_name_type' => "string",
    'index_posts_per_page' => "10",
    'index_posts_per_page_type' => "int",
    'category_posts_per_page' => "10",
    'category_posts_per_page_type' => "int",
    'tags_posts_per_page' => "10",
    'tags_posts_per_page_type' => "int",
    'disable_comments_modul' => false,
    'disable_comments_modul_type' => "bool",
    'max_unaproved_comments' => "10",
    'max_unaproved_comments_type' => "int",
    'approve_comments_from_users_with_approved_comments' => true,
    'approve_comments_from_users_with_approved_comments_type' => "bool",

    'disable_search_modul' => false,
    'disable_search_modul_type' => "bool",
    'main_menu_name' => "Main",
    'main_menu_name_type' => "string",
];
